# Generated by Django 3.2.6 on 2022-01-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220130_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='ques_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='questions',
            name='q_a',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='questions',
            name='q_b',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='questions',
            name='q_c',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='questions',
            name='q_d',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
