# Generated by Django 3.2.6 on 2022-01-30 14:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_auto_20220130_1930'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='canvas',
            new_name='usercanvas',
        ),
    ]
