# Generated by Django 3.2.6 on 2022-02-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_canvas_usercanvas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercanvas',
            name='questions',
        ),
        migrations.AddField(
            model_name='usercanvas',
            name='q_a',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='usercanvas',
            name='q_b',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='usercanvas',
            name='q_c',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='usercanvas',
            name='q_d',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='usercanvas',
            name='ques_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='usercanvas',
            name='scenario',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
