# Generated by Django 3.2.6 on 2022-02-08 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_selectivequestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='usercanvasSelective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.TextField(blank=True, max_length=3000)),
                ('ques_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('q_a', models.CharField(blank=True, max_length=300)),
                ('q_b', models.CharField(blank=True, max_length=300)),
                ('q_c', models.CharField(blank=True, max_length=300)),
                ('q_d', models.CharField(blank=True, max_length=300)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
