# Generated by Django 3.2.6 on 2022-02-13 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_userinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.IntegerField(choices=[(5, 'Five Point'), (10, 'Ten Point'), (20, 'Twenty Point'), (50, 'Fifty Point'), (100, 'Hundred Point')], default=None, null=True)),
                ('trxID', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
