# Generated by Django 3.2.6 on 2022-02-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='testDocx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docx', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
