# Generated by Django 3.2.6 on 2022-02-16 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_testdocx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testdocx',
            old_name='docx',
            new_name='docs',
        ),
    ]
