# Generated by Django 3.2.6 on 2022-03-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20220218_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='english_docQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.IntegerField(choices=[(1, 'Class One'), (2, 'Class Two'), (3, 'Class Three'), (4, 'Class Four'), (5, 'Class Five'), (6, 'Class Six'), (7, 'Class Seven'), (8, 'Class Eight'), (9, 'Class Nine'), (10, 'Class Ten')], default=None, null=True)),
                ('subject', models.CharField(choices=[('bangla1', 'Bangla 1st Paper'), ('bangla2', 'Bangla 2nd Paper'), ('english1', 'English 1st Paper'), ('enlish2', 'English 2nd Paper'), ('math', 'Math'), ('religion', 'Religion'), ('ict', 'ICT'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('highermath', 'Higher Math'), ('accounting', 'Accounting'), ('finance', 'Finance'), ('business', 'Business Entrepreneurship'), ('agriculture', 'Agricultural Studies'), ('gscinece', 'General Science'), ('bgs', 'Bangladesh and Global Studies')], default=None, max_length=100, null=True)),
                ('chapter', models.IntegerField(choices=[(1, 'Chapter One'), (2, 'Chapter Two'), (3, 'Chapter Three'), (4, 'Chapter Four'), (5, 'Chapter Five'), (6, 'Chapter Six'), (7, 'Chapter Seven'), (8, 'Chapter Eight'), (9, 'Chapter Nine'), (10, 'Chapter Ten')], default=None, null=True)),
                ('questionTitle', models.CharField(blank=True, max_length=300)),
                ('docs', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
