# Generated by Django 3.2.6 on 2022-03-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_english_docquestions_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='english_docquestions',
            name='paper',
            field=models.CharField(choices=[('english1', '1st Paper'), ('enlish2', '2nd Paper')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='docquestions',
            name='subject',
            field=models.CharField(choices=[('bangla1', 'Bangla 1st Paper'), ('bangla2', 'Bangla 2nd Paper'), ('math', 'Math'), ('religion', 'Religion'), ('ict', 'ICT'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('highermath', 'Higher Math'), ('accounting', 'Accounting'), ('finance', 'Finance'), ('business', 'Business Entrepreneurship'), ('agriculture', 'Agricultural Studies'), ('gscinece', 'General Science'), ('bgs', 'Bangladesh and Global Studies')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='subject',
            field=models.CharField(choices=[('bangla1', 'Bangla 1st Paper'), ('bangla2', 'Bangla 2nd Paper'), ('math', 'Math'), ('religion', 'Religion'), ('ict', 'ICT'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('highermath', 'Higher Math'), ('accounting', 'Accounting'), ('finance', 'Finance'), ('business', 'Business Entrepreneurship'), ('agriculture', 'Agricultural Studies'), ('gscinece', 'General Science'), ('bgs', 'Bangladesh and Global Studies')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='selectivequestion',
            name='subject',
            field=models.CharField(choices=[('bangla1', 'Bangla 1st Paper'), ('bangla2', 'Bangla 2nd Paper'), ('math', 'Math'), ('religion', 'Religion'), ('ict', 'ICT'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('highermath', 'Higher Math'), ('accounting', 'Accounting'), ('finance', 'Finance'), ('business', 'Business Entrepreneurship'), ('agriculture', 'Agricultural Studies'), ('gscinece', 'General Science'), ('bgs', 'Bangladesh and Global Studies')], default=None, max_length=100, null=True),
        ),
    ]
