# Generated by Django 3.2.6 on 2022-03-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20220303_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='english_docquestions',
            name='paper',
            field=models.CharField(choices=[('english1', '1st Paper'), ('english2', '2nd Paper')], default=None, max_length=100, null=True),
        ),
    ]
