# Generated by Django 3.2.6 on 2022-03-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_class_suggesstion_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_suggesstion',
            name='suggesstion',
        ),
        migrations.AddField(
            model_name='class_suggesstion',
            name='artsAndCrafts',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='class_suggesstion',
            name='bangla',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='class_suggesstion',
            name='boudhuReligion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='class_suggesstion',
            name='comment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='class_suggesstion',
            name='cristantianReligion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='class_suggesstion',
            name='english',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='class_suggesstion',
            name='hinduReligion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='class_suggesstion',
            name='islamReligion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='class_suggesstion',
            name='math',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='class_suggesstion',
            name='music',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='class_suggesstion',
            name='physicalEducation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='class_suggesstion',
            name='science',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='class_suggesstion',
            name='social',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
